#!/usr/bin/env bash
# Deploy mirror_ai_agent to a Volcengine Ubuntu/Debian server.
#
# Local usage:
#   cp .deploy.env.example .deploy.env
#   # edit .deploy.env
#   bash scripts/deploy_volcengine.sh
#
# Assumptions:
# - You can SSH to the server as root (or another user with passwordless sudo,
#   though root is the recommended path for this script).
# - DNS already points DEPLOY_DOMAIN (e.g. api.mymirrorai.com) to the server IP
#   when you are ready to add/reload the host-level Caddy snippet.
# - Volcengine security group allows inbound TCP 22, 80, and 443.
# - The existing website's host-level Caddy already owns :80/:443. This script
#   does NOT overwrite /etc/caddy/Caddyfile or restart Caddy.

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DEPLOY_ENV_FILE="${DEPLOY_ENV_FILE:-${ROOT_DIR}/.deploy.env}"
CADDY_SNIPPET_TEMPLATE="${ROOT_DIR}/deploy/Caddyfile.existing-proxy-api-snippet.template"

log() {
  printf '[deploy] %s\n' "$*"
}

die() {
  printf '[deploy] FATAL: %s\n' "$*" >&2
  exit 1
}

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || die "missing local command: $1"
}

load_deploy_env() {
  [[ -f "$DEPLOY_ENV_FILE" ]] || die "missing ${DEPLOY_ENV_FILE}; copy .deploy.env.example to .deploy.env first"
  # shellcheck disable=SC1090
  set -a
  source "$DEPLOY_ENV_FILE"
  set +a
}

require_var() {
  local name="$1"
  local value="${!name:-}"
  [[ -n "$value" ]] || die "${name} is required in ${DEPLOY_ENV_FILE}"
}

# Common -o flags that work for both ssh and scp. The port flag and ControlMaster
# options are appended later because ssh uses -p while scp uses -P, and because
# ControlMaster options sometimes need to vary per tool.
_common_ssh_opts() {
  local args=()
  args+=("-o" "ServerAliveInterval=15")
  args+=("-o" "ServerAliveCountMax=4")
  args+=("-o" "ConnectTimeout=20")
  # Optional SSH connection multiplexing. Disabled by default because some
  # Windows OpenSSH builds cannot create Unix-domain control sockets and
  # abort with "Failed to connect to new control master". Opt in by setting
  # DEPLOY_USE_CONTROLMASTER=1 on Linux/macOS to reduce password prompts.
  if [[ "${DEPLOY_USE_CONTROLMASTER:-0}" == "1" ]]; then
    mkdir -p "${HOME}/.ssh/cm-mirror" 2>/dev/null || true
    chmod 700 "${HOME}/.ssh" "${HOME}/.ssh/cm-mirror" 2>/dev/null || true
    args+=("-o" "ControlMaster=auto")
    args+=("-o" "ControlPath=${HOME}/.ssh/cm-mirror/%r@%h-%p")
    args+=("-o" "ControlPersist=600")
  fi
  if [[ -n "${SSH_KEY_PATH:-}" ]]; then
    args+=("-i" "${SSH_KEY_PATH}")
  fi
  printf '%s\n' "${args[@]}"
}

# ssh accepts the port via lowercase -p.
ssh_args() {
  local args=()
  args+=("-p" "${DEPLOY_PORT:-22}")
  while IFS= read -r arg; do args+=("$arg"); done < <(_common_ssh_opts)
  printf '%s\n' "${args[@]}"
}

# scp accepts the port via uppercase -P. Lowercase -p means "preserve mtimes"
# and that bug caused the deploy to fail with `scp: stat local "22"`.
scp_args() {
  local args=()
  args+=("-P" "${DEPLOY_PORT:-22}")
  while IFS= read -r arg; do args+=("$arg"); done < <(_common_ssh_opts)
  printf '%s\n' "${args[@]}"
}

remote_target() {
  printf '%s@%s' "${DEPLOY_USER:-root}" "${DEPLOY_HOST}"
}

ssh_remote() {
  local target
  target="$(remote_target)"
  local args=()
  while IFS= read -r arg; do args+=("$arg"); done < <(ssh_args)
  ssh "${args[@]}" "$target" "$@"
}

scp_to_remote() {
  local src="$1"
  local dest="$2"
  local target
  target="$(remote_target)"
  local args=()
  while IFS= read -r arg; do args+=("$arg"); done < <(scp_args)
  scp "${args[@]}" "$src" "${target}:${dest}"
}

render_caddy_snippet() {
  [[ -f "$CADDY_SNIPPET_TEMPLATE" ]] || die "missing ${CADDY_SNIPPET_TEMPLATE}"
  sed \
    -e "s|\${DEPLOY_DOMAIN}|${DEPLOY_DOMAIN}|g" \
    "$CADDY_SNIPPET_TEMPLATE"
}

write_server_env_file() {
  local tmp_file="$1"
  cat >"$tmp_file" <<EOF
# Generated by scripts/deploy_volcengine.sh. Edit .deploy.env locally and rerun.

DEMO_API_TOKEN=${DEMO_API_TOKEN}
BILLING_ADMIN_BYPASS=${BILLING_ADMIN_BYPASS:-0}
BILLING_INFLIGHT_LIMIT=${BILLING_INFLIGHT_LIMIT:-2}
BILLING_RATE_LIMIT_PER_MIN=${BILLING_RATE_LIMIT_PER_MIN:-10}
REGISTER_INITIAL_CREDITS=${REGISTER_INITIAL_CREDITS:-0}

LLM_MODE=${LLM_MODE:-}
LLM_ROUTE_CONFIG=config/llm_routes.json
LLM_ROUTING_ENABLED=1
GPTPROTO_API_BASE=${GPTPROTO_API_BASE:-https://gptproto.com/v1}
GPTPROTO_API_KEY=${GPTPROTO_API_KEY:-}
QWEN_API_BASE=${QWEN_API_BASE:-https://dashscope.aliyuncs.com/compatible-mode/v1}
QWEN_API_KEY=${QWEN_API_KEY:-}
LLM_MODEL=${LLM_MODEL:-gemini-3.1-pro-preview}
LLM_TIMEOUT_SECONDS=${LLM_TIMEOUT_SECONDS:-120}
LLM_MAX_RETRIES=${LLM_MAX_RETRIES:-2}
LLM_PARALLEL_WORKERS=${LLM_PARALLEL_WORKERS:-}
LLM_DEBUG=${LLM_DEBUG:-0}
LLM_TRACE_RAW=${LLM_TRACE_RAW:-0}
LLM_BYPASS_CACHE=${LLM_BYPASS_CACHE:-0}

STRIPE_MODE=${STRIPE_MODE:-test}
STRIPE_SECRET_KEY_TEST=${STRIPE_SECRET_KEY_TEST:-}
STRIPE_PUBLISHABLE_KEY_TEST=${STRIPE_PUBLISHABLE_KEY_TEST:-}
STRIPE_WEBHOOK_SECRET_TEST=${STRIPE_WEBHOOK_SECRET_TEST:-}
STRIPE_SECRET_KEY_LIVE=${STRIPE_SECRET_KEY_LIVE:-}
STRIPE_PUBLISHABLE_KEY_LIVE=${STRIPE_PUBLISHABLE_KEY_LIVE:-}
STRIPE_WEBHOOK_SECRET_LIVE=${STRIPE_WEBHOOK_SECRET_LIVE:-}
STRIPE_SUCCESS_URL=https://${DEPLOY_DOMAIN}/billing.html?status=success&session_id={CHECKOUT_SESSION_ID}
STRIPE_CANCEL_URL=https://${DEPLOY_DOMAIN}/billing.html?status=cancelled
STRIPE_PAYMENT_METHODS=${STRIPE_PAYMENT_METHODS:-card}

SENTRY_DSN=${SENTRY_DSN:-}
SENTRY_ENVIRONMENT=${SENTRY_ENVIRONMENT:-production}
SENTRY_TRACES_SAMPLE_RATE=${SENTRY_TRACES_SAMPLE_RATE:-0.05}
EOF
}

main() {
  require_cmd ssh
  require_cmd scp
  require_cmd sed
  require_cmd curl
  load_deploy_env

  DEPLOY_USER="${DEPLOY_USER:-root}"
  DEPLOY_PORT="${DEPLOY_PORT:-22}"
  DEPLOY_BRANCH="${DEPLOY_BRANCH:-master}"
  DEPLOY_PATH="${DEPLOY_PATH:-/opt/mirror_ai_agent}"
  DEPLOY_STRICT_PREFLIGHT="${DEPLOY_STRICT_PREFLIGHT:-0}"
  DEPLOY_VERIFY_PUBLIC="${DEPLOY_VERIFY_PUBLIC:-0}"

  require_var DEPLOY_HOST
  require_var DEPLOY_DOMAIN
  require_var DEPLOY_REPO
  require_var DEMO_API_TOKEN
  require_var GPTPROTO_API_KEY
  require_var QWEN_API_KEY

  if [[ "${STRIPE_MODE:-test}" == "live" ]]; then
    require_var STRIPE_SECRET_KEY_LIVE
    require_var STRIPE_PUBLISHABLE_KEY_LIVE
    require_var STRIPE_WEBHOOK_SECRET_LIVE
  fi

  log "target: $(remote_target)"
  log "domain: https://${DEPLOY_DOMAIN}"
  log "path: ${DEPLOY_PATH}"
  if [[ -z "${SSH_KEY_PATH:-}" ]]; then
    log "tip: set up SSH key auth (ssh-copy-id root@${DEPLOY_HOST}) to avoid repeated password prompts during deploy"
  fi

  local tmp_dir="" env_tmp="" caddy_snippet_tmp=""
  tmp_dir="$(mktemp -d)"
  env_tmp="${tmp_dir}/server.env"
  caddy_snippet_tmp="${tmp_dir}/api-caddy-snippet.Caddyfile"
  trap '[[ -n "${tmp_dir:-}" ]] && rm -rf "$tmp_dir"' EXIT

  write_server_env_file "$env_tmp"
  render_caddy_snippet >"$caddy_snippet_tmp"

  log "checking SSH connectivity"
  ssh_remote "echo connected: \$(hostname)"

  log "installing base host dependencies (git, sqlite3, curl, python3)"
  # apt-get update can emit a non-fatal warning about the host's Caddy apt repo
  # (expired GPG key on the existing mymirrorai.com server). We ignore it because
  # we only need base packages here and never install Caddy via apt ourselves.
  ssh_remote "set -e
export DEBIAN_FRONTEND=noninteractive
apt-get update || true
apt-get install -y git curl ca-certificates sqlite3 python3"

  if ssh_remote "command -v docker >/dev/null 2>&1 && docker compose version >/dev/null 2>&1"; then
    log "docker + compose already installed on host, skipping bootstrap"
    ssh_remote "systemctl enable --now docker"
  else
    log "docker missing on host; installing via get.docker.com in a detached background process"
    log "  (the install briefly reconfigures iptables which is known to drop SSH on Volcengine ECS)"
    log "  (the install continues server-side even if our SSH session is interrupted)"

    # Kick off the install via setsid + nohup so it survives any SSH disconnect
    # caused by Docker reconfiguring iptables. The detached process writes a
    # marker file when it finishes; we poll for that marker from the client.
    ssh_remote 'set -e
export DEBIAN_FRONTEND=noninteractive
rm -f /tmp/.mirror-docker-done /tmp/.mirror-docker-failed
cat > /tmp/mirror-docker-install.sh <<"BOOTSTRAP"
#!/usr/bin/env bash
set -e
export DEBIAN_FRONTEND=noninteractive
# If a previous run was interrupted (e.g. SSH disconnect mid apt-install),
# dpkg may have half-configured packages on disk. Heal that first.
dpkg --configure -a || true
apt-get install -f -y || true
curl -fsSL https://get.docker.com -o /tmp/get-docker.sh
sh /tmp/get-docker.sh
rm -f /tmp/get-docker.sh
systemctl enable --now docker
docker compose version
BOOTSTRAP
chmod +x /tmp/mirror-docker-install.sh
# setsid detaches from the SSH session; nohup ignores SIGHUP; redirects ensure
# no terminal i/o keeps us tied to the parent shell.
setsid nohup bash -c "if /tmp/mirror-docker-install.sh > /var/log/mirror-docker-install.log 2>&1; then touch /tmp/.mirror-docker-done; else touch /tmp/.mirror-docker-failed; fi" </dev/null >/dev/null 2>&1 &
echo "[remote] docker install kicked off in background, log: /var/log/mirror-docker-install.log"'

    # Strategy: do most of the waiting on the client side so we don't hold an
    # SSH session open while Docker reconfigures iptables (which would drop the
    # session). Then make ONE server-side wait call to finish off.
    log "sleeping 120s on the client while docker installs in the background..."
    log "  (the iptables reset that previously killed our SSH happens during this window)"
    local i
    for i in 1 2 3 4 5 6 7 8 9 10 11 12; do
      sleep 10
      printf '[deploy] still sleeping (%d/12)\n' "$i"
    done

    log "checking docker install status..."
    local marker=""
    marker="$(ssh_remote 'if [[ -f /tmp/.mirror-docker-done ]]; then echo done; elif [[ -f /tmp/.mirror-docker-failed ]]; then echo failed; else echo pending; fi' 2>/dev/null || echo error)"
    marker="${marker//$'\r'/}"
    marker="${marker//$'\n'/}"

    if [[ "$marker" == "done" ]]; then
      log "docker install completed within the initial 2-minute window"
    elif [[ "$marker" == "failed" ]]; then
      log "docker install reported failure; dumping last 100 lines of install log:"
      ssh_remote "tail -100 /var/log/mirror-docker-install.log" || true
      die "docker install failed"
    else
      log "docker install still running (marker=${marker}); doing one server-side wait (up to 4 more minutes)..."
      # Single SSH call that waits server-side. Only one password prompt.
      # exit 0 = done, 1 = failed (with log tail), 2 = timeout.
      local rc=0
      ssh_remote "for i in \$(seq 1 48); do
  if [[ -f /tmp/.mirror-docker-done ]]; then
    exit 0
  fi
  if [[ -f /tmp/.mirror-docker-failed ]]; then
    echo '--- /var/log/mirror-docker-install.log (last 100 lines) ---'
    tail -100 /var/log/mirror-docker-install.log
    exit 1
  fi
  sleep 5
done
echo '--- timeout, last 100 lines of install log ---'
tail -100 /var/log/mirror-docker-install.log
exit 2" || rc=$?
      case "$rc" in
        0) log "docker install completed (after extended wait)" ;;
        1) die "docker install failed; see log above" ;;
        2) die "docker install did not finish in time (~6 min total)" ;;
        *) die "could not verify docker install state (rc=$rc)" ;;
      esac
    fi

    ssh_remote "systemctl enable --now docker
docker compose version"
  fi

  log "cloning/updating repo"
  ssh_remote "set -euo pipefail
mkdir -p \"$(dirname "${DEPLOY_PATH}")\"
if [[ -d \"${DEPLOY_PATH}/.git\" ]]; then
  cd \"${DEPLOY_PATH}\"
  git remote set-url origin \"${DEPLOY_REPO}\"
  git fetch origin \"${DEPLOY_BRANCH}\"
  git checkout \"${DEPLOY_BRANCH}\"
  git pull --ff-only origin \"${DEPLOY_BRANCH}\"
else
  rm -rf \"${DEPLOY_PATH}\"
  git clone --branch \"${DEPLOY_BRANCH}\" \"${DEPLOY_REPO}\" \"${DEPLOY_PATH}\"
fi
mkdir -p \"${DEPLOY_PATH}/storage\""

  log "uploading production .env and generated Caddy snippet"
  scp_to_remote "$env_tmp" "${DEPLOY_PATH}/.env"
  ssh_remote "mkdir -p \"${DEPLOY_PATH}/deploy\""
  scp_to_remote "$caddy_snippet_tmp" "${DEPLOY_PATH}/deploy/generated-api-caddy-snippet.Caddyfile"

  log "running production preflight"
  if [[ "$DEPLOY_STRICT_PREFLIGHT" == "1" ]]; then
    ssh_remote "cd \"${DEPLOY_PATH}\" && python3 scripts/check_prod_env.py --env .env --strict"
  else
    ssh_remote "cd \"${DEPLOY_PATH}\" && python3 scripts/check_prod_env.py --env .env"
  fi

  log "building and starting API container on 127.0.0.1:8000"
  ssh_remote "cd \"${DEPLOY_PATH}\" && docker compose -f docker-compose.api-only.yml up -d --build && docker compose -f docker-compose.api-only.yml ps"

  log "waiting for local API health endpoint and verifying routes (single SSH session)"
  # All checks in one server-side loop so we only prompt for the password once.
  ssh_remote "for i in \$(seq 1 30); do
  if curl -fsS http://127.0.0.1:8000/health >/dev/null 2>&1; then
    echo '[remote] /health OK'
    if curl -fsS http://127.0.0.1:8000/docs >/dev/null 2>&1 && curl -fsS http://127.0.0.1:8000/openapi.json >/dev/null 2>&1; then
      echo '[remote] /docs and /openapi.json OK'
      exit 0
    fi
    echo '[remote] /docs or /openapi.json failed; retrying...'
  fi
  sleep 5
done
echo '[remote] timed out waiting for API endpoints'
docker compose -f ${DEPLOY_PATH}/docker-compose.api-only.yml logs --tail=200 || true
exit 1" || die "local API did not become healthy on the server"

  if [[ "$DEPLOY_VERIFY_PUBLIC" == "1" ]]; then
    log "verifying public HTTPS routes"
    curl -fsS "https://${DEPLOY_DOMAIN}/health" >/dev/null
    curl -fsS "https://${DEPLOY_DOMAIN}/docs" >/dev/null
    curl -fsS "https://${DEPLOY_DOMAIN}/openapi.json" >/dev/null

    local blocked_status
    blocked_status="$(curl -k -s -o /dev/null -w '%{http_code}' "https://${DEPLOY_DOMAIN}/")"
    [[ "$blocked_status" == "404" ]] || die "expected / to be 404, got ${blocked_status}"
    blocked_status="$(curl -k -s -o /dev/null -w '%{http_code}' "https://${DEPLOY_DOMAIN}/admin.html")"
    [[ "$blocked_status" == "404" ]] || die "expected /admin.html to be 404, got ${blocked_status}"
  else
    log "skipping public HTTPS verification (set DEPLOY_VERIFY_PUBLIC=1 after adding/reloading the Caddy snippet)"
  fi

  log "deployment complete"
  log "API is running locally on the server: http://127.0.0.1:8000"
  log "Caddy snippet uploaded to: ${DEPLOY_PATH}/deploy/generated-api-caddy-snippet.Caddyfile"
  log "Next: append that snippet to /etc/caddy/Caddyfile, run 'caddy validate --config /etc/caddy/Caddyfile', then 'systemctl reload caddy'."
  log "After reload: set DEPLOY_VERIFY_PUBLIC=1 and rerun this script, or manually check https://${DEPLOY_DOMAIN}/docs"
}

main "$@"
