#!/usr/bin/env bash
# Deploy mirror_ai_agent to a Volcengine Ubuntu/Debian server.
#
# Local usage:
#   cp .deploy.env.example .deploy.env
#   # edit .deploy.env
#   bash scripts/deploy_volcengine.sh
#
# Assumptions:
# - You can SSH to the server as root (or another user with passwordless sudo,
#   though root is the recommended path for this script).
# - DNS already points DEPLOY_DOMAIN (e.g. api.mymirrorai.com) to the server IP
#   when you are ready to add/reload the host-level Caddy snippet.
# - Volcengine security group allows inbound TCP 22, 80, and 443.
# - The existing website's host-level Caddy already owns :80/:443. This script
#   does NOT overwrite /etc/caddy/Caddyfile or restart Caddy.

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DEPLOY_ENV_FILE="${DEPLOY_ENV_FILE:-${ROOT_DIR}/.deploy.env}"
CADDY_SNIPPET_TEMPLATE="${ROOT_DIR}/deploy/Caddyfile.existing-proxy-api-snippet.template"

log() {
  printf '[deploy] %s\n' "$*"
}

die() {
  printf '[deploy] FATAL: %s\n' "$*" >&2
  exit 1
}

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || die "missing local command: $1"
}

load_deploy_env() {
  [[ -f "$DEPLOY_ENV_FILE" ]] || die "missing ${DEPLOY_ENV_FILE}; copy .deploy.env.example to .deploy.env first"
  # shellcheck disable=SC1090
  set -a
  source "$DEPLOY_ENV_FILE"
  set +a
}

require_var() {
  local name="$1"
  local value="${!name:-}"
  [[ -n "$value" ]] || die "${name} is required in ${DEPLOY_ENV_FILE}"
}

ssh_args() {
  local args=()
  args+=("-p" "${DEPLOY_PORT:-22}")
  args+=("-o" "ServerAliveInterval=30")
  args+=("-o" "ServerAliveCountMax=6")
  if [[ -n "${SSH_KEY_PATH:-}" ]]; then
    args+=("-i" "${SSH_KEY_PATH}")
  fi
  printf '%s\n' "${args[@]}"
}

remote_target() {
  printf '%s@%s' "${DEPLOY_USER:-root}" "${DEPLOY_HOST}"
}

ssh_remote() {
  local target
  target="$(remote_target)"
  local args=()
  while IFS= read -r arg; do args+=("$arg"); done < <(ssh_args)
  ssh "${args[@]}" "$target" "$@"
}

scp_to_remote() {
  local src="$1"
  local dest="$2"
  local target
  target="$(remote_target)"
  local args=()
  while IFS= read -r arg; do args+=("$arg"); done < <(ssh_args)
  scp "${args[@]}" "$src" "${target}:${dest}"
}

render_caddy_snippet() {
  [[ -f "$CADDY_SNIPPET_TEMPLATE" ]] || die "missing ${CADDY_SNIPPET_TEMPLATE}"
  sed \
    -e "s|\${DEPLOY_DOMAIN}|${DEPLOY_DOMAIN}|g" \
    "$CADDY_SNIPPET_TEMPLATE"
}

write_server_env_file() {
  local tmp_file="$1"
  cat >"$tmp_file" <<EOF
# Generated by scripts/deploy_volcengine.sh. Edit .deploy.env locally and rerun.

DEMO_API_TOKEN=${DEMO_API_TOKEN}
BILLING_ADMIN_BYPASS=${BILLING_ADMIN_BYPASS:-0}
BILLING_INFLIGHT_LIMIT=${BILLING_INFLIGHT_LIMIT:-2}
BILLING_RATE_LIMIT_PER_MIN=${BILLING_RATE_LIMIT_PER_MIN:-10}
REGISTER_INITIAL_CREDITS=${REGISTER_INITIAL_CREDITS:-0}

LLM_MODE=${LLM_MODE:-}
LLM_ROUTE_CONFIG=config/llm_routes.json
LLM_ROUTING_ENABLED=1
GPTPROTO_API_BASE=${GPTPROTO_API_BASE:-https://gptproto.com/v1}
GPTPROTO_API_KEY=${GPTPROTO_API_KEY:-}
QWEN_API_BASE=${QWEN_API_BASE:-https://dashscope.aliyuncs.com/compatible-mode/v1}
QWEN_API_KEY=${QWEN_API_KEY:-}
LLM_MODEL=${LLM_MODEL:-gemini-3.1-pro-preview}
LLM_TIMEOUT_SECONDS=${LLM_TIMEOUT_SECONDS:-120}
LLM_MAX_RETRIES=${LLM_MAX_RETRIES:-2}
LLM_PARALLEL_WORKERS=${LLM_PARALLEL_WORKERS:-}
LLM_DEBUG=${LLM_DEBUG:-0}
LLM_TRACE_RAW=${LLM_TRACE_RAW:-0}
LLM_BYPASS_CACHE=${LLM_BYPASS_CACHE:-0}

STRIPE_MODE=${STRIPE_MODE:-test}
STRIPE_SECRET_KEY_TEST=${STRIPE_SECRET_KEY_TEST:-}
STRIPE_PUBLISHABLE_KEY_TEST=${STRIPE_PUBLISHABLE_KEY_TEST:-}
STRIPE_WEBHOOK_SECRET_TEST=${STRIPE_WEBHOOK_SECRET_TEST:-}
STRIPE_SECRET_KEY_LIVE=${STRIPE_SECRET_KEY_LIVE:-}
STRIPE_PUBLISHABLE_KEY_LIVE=${STRIPE_PUBLISHABLE_KEY_LIVE:-}
STRIPE_WEBHOOK_SECRET_LIVE=${STRIPE_WEBHOOK_SECRET_LIVE:-}
STRIPE_SUCCESS_URL=https://${DEPLOY_DOMAIN}/billing.html?status=success&session_id={CHECKOUT_SESSION_ID}
STRIPE_CANCEL_URL=https://${DEPLOY_DOMAIN}/billing.html?status=cancelled
STRIPE_PAYMENT_METHODS=${STRIPE_PAYMENT_METHODS:-card}

SENTRY_DSN=${SENTRY_DSN:-}
SENTRY_ENVIRONMENT=${SENTRY_ENVIRONMENT:-production}
SENTRY_TRACES_SAMPLE_RATE=${SENTRY_TRACES_SAMPLE_RATE:-0.05}
EOF
}

main() {
  require_cmd ssh
  require_cmd scp
  require_cmd sed
  require_cmd curl
  load_deploy_env

  DEPLOY_USER="${DEPLOY_USER:-root}"
  DEPLOY_PORT="${DEPLOY_PORT:-22}"
  DEPLOY_BRANCH="${DEPLOY_BRANCH:-master}"
  DEPLOY_PATH="${DEPLOY_PATH:-/opt/mirror_ai_agent}"
  DEPLOY_STRICT_PREFLIGHT="${DEPLOY_STRICT_PREFLIGHT:-0}"
  DEPLOY_VERIFY_PUBLIC="${DEPLOY_VERIFY_PUBLIC:-0}"

  require_var DEPLOY_HOST
  require_var DEPLOY_DOMAIN
  require_var DEPLOY_REPO
  require_var DEMO_API_TOKEN
  require_var GPTPROTO_API_KEY
  require_var QWEN_API_KEY

  if [[ "${STRIPE_MODE:-test}" == "live" ]]; then
    require_var STRIPE_SECRET_KEY_LIVE
    require_var STRIPE_PUBLISHABLE_KEY_LIVE
    require_var STRIPE_WEBHOOK_SECRET_LIVE
  fi

  log "target: $(remote_target)"
  log "domain: https://${DEPLOY_DOMAIN}"
  log "path: ${DEPLOY_PATH}"

  local tmp_dir="" env_tmp="" caddy_snippet_tmp=""
  tmp_dir="$(mktemp -d)"
  env_tmp="${tmp_dir}/server.env"
  caddy_snippet_tmp="${tmp_dir}/api-caddy-snippet.Caddyfile"
  trap '[[ -n "${tmp_dir:-}" ]] && rm -rf "$tmp_dir"' EXIT

  write_server_env_file "$env_tmp"
  render_caddy_snippet >"$caddy_snippet_tmp"

  log "checking SSH connectivity"
  ssh_remote "echo connected: \$(hostname)"

  log "installing host dependencies (git, docker, compose plugin, sqlite3, curl)"
  ssh_remote "set -euo pipefail
export DEBIAN_FRONTEND=noninteractive
apt-get update || true
apt-get install -y git curl ca-certificates sqlite3 python3

# Install Docker if missing
if ! command -v docker >/dev/null 2>&1; then
  curl -fsSL https://get.docker.com -o get-docker.sh
  sh get-docker.sh
  rm get-docker.sh
fi

systemctl enable --now docker
docker compose version"

  log "cloning/updating repo"
  ssh_remote "set -euo pipefail
mkdir -p \"$(dirname "${DEPLOY_PATH}")\"
if [[ -d \"${DEPLOY_PATH}/.git\" ]]; then
  cd \"${DEPLOY_PATH}\"
  git remote set-url origin \"${DEPLOY_REPO}\"
  git fetch origin \"${DEPLOY_BRANCH}\"
  git checkout \"${DEPLOY_BRANCH}\"
  git pull --ff-only origin \"${DEPLOY_BRANCH}\"
else
  rm -rf \"${DEPLOY_PATH}\"
  git clone --branch \"${DEPLOY_BRANCH}\" \"${DEPLOY_REPO}\" \"${DEPLOY_PATH}\"
fi
mkdir -p \"${DEPLOY_PATH}/storage\""

  log "uploading production .env and generated Caddy snippet"
  scp_to_remote "$env_tmp" "${DEPLOY_PATH}/.env"
  ssh_remote "mkdir -p \"${DEPLOY_PATH}/deploy\""
  scp_to_remote "$caddy_snippet_tmp" "${DEPLOY_PATH}/deploy/generated-api-caddy-snippet.Caddyfile"

  log "running production preflight"
  if [[ "$DEPLOY_STRICT_PREFLIGHT" == "1" ]]; then
    ssh_remote "cd \"${DEPLOY_PATH}\" && python3 scripts/check_prod_env.py --env .env --strict"
  else
    ssh_remote "cd \"${DEPLOY_PATH}\" && python3 scripts/check_prod_env.py --env .env"
  fi

  log "building and starting API container on 127.0.0.1:8000"
  ssh_remote "cd \"${DEPLOY_PATH}\" && docker compose -f docker-compose.api-only.yml up -d --build && docker compose -f docker-compose.api-only.yml ps"

  log "waiting for local API health endpoint"
  local attempt=1
  while (( attempt <= 30 )); do
    if ssh_remote "curl -fsS http://127.0.0.1:8000/health >/dev/null"; then
      break
    fi
    printf '[deploy] waiting for health (%d/30)\n' "$attempt"
    sleep 5
    attempt=$((attempt + 1))
  done
  (( attempt <= 30 )) || die "http://127.0.0.1:8000/health did not become healthy on the server"

  log "verifying local API routes"
  ssh_remote "curl -fsS http://127.0.0.1:8000/health >/dev/null"
  ssh_remote "curl -fsS http://127.0.0.1:8000/docs >/dev/null"
  ssh_remote "curl -fsS http://127.0.0.1:8000/openapi.json >/dev/null"

  if [[ "$DEPLOY_VERIFY_PUBLIC" == "1" ]]; then
    log "verifying public HTTPS routes"
    curl -fsS "https://${DEPLOY_DOMAIN}/health" >/dev/null
    curl -fsS "https://${DEPLOY_DOMAIN}/docs" >/dev/null
    curl -fsS "https://${DEPLOY_DOMAIN}/openapi.json" >/dev/null

    local blocked_status
    blocked_status="$(curl -k -s -o /dev/null -w '%{http_code}' "https://${DEPLOY_DOMAIN}/")"
    [[ "$blocked_status" == "404" ]] || die "expected / to be 404, got ${blocked_status}"
    blocked_status="$(curl -k -s -o /dev/null -w '%{http_code}' "https://${DEPLOY_DOMAIN}/admin.html")"
    [[ "$blocked_status" == "404" ]] || die "expected /admin.html to be 404, got ${blocked_status}"
  else
    log "skipping public HTTPS verification (set DEPLOY_VERIFY_PUBLIC=1 after adding/reloading the Caddy snippet)"
  fi

  log "deployment complete"
  log "API is running locally on the server: http://127.0.0.1:8000"
  log "Caddy snippet uploaded to: ${DEPLOY_PATH}/deploy/generated-api-caddy-snippet.Caddyfile"
  log "Next: append that snippet to /etc/caddy/Caddyfile, run 'caddy validate --config /etc/caddy/Caddyfile', then 'systemctl reload caddy'."
  log "After reload: set DEPLOY_VERIFY_PUBLIC=1 and rerun this script, or manually check https://${DEPLOY_DOMAIN}/docs"
}

main "$@"
