#!/usr/bin/env bash
# Deploy mirror_ai_agent to Volcengine using a prebuilt private image.
#
# Difference from deploy_volcengine.sh:
#   - Does NOT git clone/pull the repo on the server.
#   - Does NOT docker build on the server.
#   - Uploads only:
#       /opt/mirror_ai_agent/.env
#       /opt/mirror_ai_agent/docker-compose.image-only.yml
#       /opt/mirror_ai_agent/deploy/generated-api-caddy-snippet.Caddyfile
#   - Runs docker compose pull/up with IMAGE_REF from .deploy.env.
#
# Local usage (Git Bash / WSL):
#   IMAGE_REF=... REGISTRY_*... in .deploy.env
#   bash scripts/deploy_volcengine_image.sh
#
# Optional one-time migration after success:
#   set DEPLOY_IMAGE_PRUNE_SOURCE=1 to remove leftover source files from the
#   server directory while preserving .env, storage/, deploy/, and compose.

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DEPLOY_ENV_FILE="${DEPLOY_ENV_FILE:-${ROOT_DIR}/.deploy.env}"
CADDY_SNIPPET_TEMPLATE="${ROOT_DIR}/deploy/Caddyfile.existing-proxy-api-snippet.template"
IMAGE_COMPOSE_TEMPLATE="${ROOT_DIR}/docker-compose.image-only.yml"

log() {
  printf '[image-deploy] %s\n' "$*"
}

die() {
  printf '[image-deploy] FATAL: %s\n' "$*" >&2
  exit 1
}

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || die "missing local command: $1"
}

load_deploy_env() {
  [[ -f "$DEPLOY_ENV_FILE" ]] || die "missing ${DEPLOY_ENV_FILE}; copy .deploy.env.example to .deploy.env first"
  # shellcheck disable=SC1090
  set -a
  source "$DEPLOY_ENV_FILE"
  set +a
}

require_var() {
  local name="$1"
  local value="${!name:-}"
  [[ -n "$value" ]] || die "${name} is required in ${DEPLOY_ENV_FILE}"
}

_common_ssh_opts() {
  local args=()
  args+=("-o" "ServerAliveInterval=15")
  args+=("-o" "ServerAliveCountMax=4")
  args+=("-o" "ConnectTimeout=20")
  if [[ "${DEPLOY_USE_CONTROLMASTER:-0}" == "1" ]]; then
    mkdir -p "${HOME}/.ssh/cm-mirror" 2>/dev/null || true
    chmod 700 "${HOME}/.ssh" "${HOME}/.ssh/cm-mirror" 2>/dev/null || true
    args+=("-o" "ControlMaster=auto")
    args+=("-o" "ControlPath=${HOME}/.ssh/cm-mirror/%r@%h-%p")
    args+=("-o" "ControlPersist=600")
  fi
  if [[ -n "${SSH_KEY_PATH:-}" ]]; then
    args+=("-i" "${SSH_KEY_PATH}")
  fi
  printf '%s\n' "${args[@]}"
}

ssh_args() {
  local args=()
  args+=("-p" "${DEPLOY_PORT:-22}")
  while IFS= read -r arg; do args+=("$arg"); done < <(_common_ssh_opts)
  printf '%s\n' "${args[@]}"
}

scp_args() {
  local args=()
  args+=("-P" "${DEPLOY_PORT:-22}")
  while IFS= read -r arg; do args+=("$arg"); done < <(_common_ssh_opts)
  printf '%s\n' "${args[@]}"
}

remote_target() {
  printf '%s@%s' "${DEPLOY_USER:-root}" "${DEPLOY_HOST}"
}

ssh_remote() {
  local target
  target="$(remote_target)"
  local args=()
  while IFS= read -r arg; do args+=("$arg"); done < <(ssh_args)
  ssh "${args[@]}" "$target" "$@"
}

scp_to_remote() {
  local src="$1"
  local dest="$2"
  local target
  target="$(remote_target)"
  local args=()
  while IFS= read -r arg; do args+=("$arg"); done < <(scp_args)
  scp "${args[@]}" "$src" "${target}:${dest}"
}

shell_quote() {
  printf '%q' "$1"
}

render_caddy_snippet() {
  [[ -f "$CADDY_SNIPPET_TEMPLATE" ]] || die "missing ${CADDY_SNIPPET_TEMPLATE}"
  sed \
    -e "s|\${DEPLOY_DOMAIN}|${DEPLOY_DOMAIN}|g" \
    "$CADDY_SNIPPET_TEMPLATE"
}

write_server_env_file() {
  local tmp_file="$1"
  cat >"$tmp_file" <<EOF
# Generated by scripts/deploy_volcengine_image.sh. Edit .deploy.env locally and rerun.

DEMO_API_TOKEN=${DEMO_API_TOKEN}
APP_SECRET_KEY=${APP_SECRET_KEY}
APP_COOKIE_SECURE=${APP_COOKIE_SECURE:-1}
BILLING_ADMIN_BYPASS=${BILLING_ADMIN_BYPASS:-0}
BILLING_INFLIGHT_LIMIT=${BILLING_INFLIGHT_LIMIT:-2}
BILLING_RATE_LIMIT_PER_MIN=${BILLING_RATE_LIMIT_PER_MIN:-10}
REGISTER_INITIAL_CREDITS=${REGISTER_INITIAL_CREDITS:-0}

LLM_MODE=${LLM_MODE:-}
LLM_ROUTE_CONFIG=config/llm_routes.json
LLM_ROUTING_ENABLED=1
GPTPROTO_API_BASE=${GPTPROTO_API_BASE:-https://gptproto.com/v1}
GPTPROTO_API_KEY=${GPTPROTO_API_KEY:-}
QWEN_API_BASE=${QWEN_API_BASE:-https://dashscope.aliyuncs.com/compatible-mode/v1}
QWEN_API_KEY=${QWEN_API_KEY:-}
LLM_MODEL=${LLM_MODEL:-gemini-3.1-pro-preview}
LLM_TIMEOUT_SECONDS=${LLM_TIMEOUT_SECONDS:-120}
LLM_MAX_RETRIES=${LLM_MAX_RETRIES:-2}
LLM_PARALLEL_WORKERS=${LLM_PARALLEL_WORKERS:-}
LLM_DEBUG=${LLM_DEBUG:-0}
LLM_TRACE_RAW=${LLM_TRACE_RAW:-0}
LLM_BYPASS_CACHE=${LLM_BYPASS_CACHE:-0}

STRIPE_MODE=${STRIPE_MODE:-test}
STRIPE_SECRET_KEY_TEST=${STRIPE_SECRET_KEY_TEST:-}
STRIPE_PUBLISHABLE_KEY_TEST=${STRIPE_PUBLISHABLE_KEY_TEST:-}
STRIPE_WEBHOOK_SECRET_TEST=${STRIPE_WEBHOOK_SECRET_TEST:-}
STRIPE_SECRET_KEY_LIVE=${STRIPE_SECRET_KEY_LIVE:-}
STRIPE_PUBLISHABLE_KEY_LIVE=${STRIPE_PUBLISHABLE_KEY_LIVE:-}
STRIPE_WEBHOOK_SECRET_LIVE=${STRIPE_WEBHOOK_SECRET_LIVE:-}
STRIPE_SUCCESS_URL=https://${DEPLOY_DOMAIN}/billing?topup=success&session_id={CHECKOUT_SESSION_ID}
STRIPE_CANCEL_URL=https://${DEPLOY_DOMAIN}/billing?topup=cancel
STRIPE_PAYMENT_METHODS=${STRIPE_PAYMENT_METHODS:-card}

SENTRY_DSN=${SENTRY_DSN:-}
SENTRY_ENVIRONMENT=${SENTRY_ENVIRONMENT:-production}
SENTRY_TRACES_SAMPLE_RATE=${SENTRY_TRACES_SAMPLE_RATE:-0.05}
EOF
}

write_compose_file() {
  local tmp_file="$1"
  [[ -f "$IMAGE_COMPOSE_TEMPLATE" ]] || die "missing ${IMAGE_COMPOSE_TEMPLATE}"
  sed \
    -e "s|\${IMAGE_REF:?IMAGE_REF is required}|${IMAGE_REF}|g" \
    "$IMAGE_COMPOSE_TEMPLATE" >"$tmp_file"
}

main() {
  require_cmd ssh
  require_cmd scp
  require_cmd sed
  require_cmd curl
  load_deploy_env

  DEPLOY_USER="${DEPLOY_USER:-root}"
  DEPLOY_PORT="${DEPLOY_PORT:-22}"
  DEPLOY_PATH="${DEPLOY_PATH:-/opt/mirror_ai_agent}"
  DEPLOY_STRICT_PREFLIGHT="${DEPLOY_STRICT_PREFLIGHT:-0}"
  DEPLOY_VERIFY_PUBLIC="${DEPLOY_VERIFY_PUBLIC:-0}"
  DEPLOY_IMAGE_PRUNE_SOURCE="${DEPLOY_IMAGE_PRUNE_SOURCE:-0}"

  require_var DEPLOY_HOST
  require_var DEPLOY_DOMAIN
  require_var DEMO_API_TOKEN
  require_var GPTPROTO_API_KEY
  require_var QWEN_API_KEY
  require_var APP_SECRET_KEY
  require_var IMAGE_REF

  if [[ "${STRIPE_MODE:-test}" == "live" ]]; then
    require_var STRIPE_SECRET_KEY_LIVE
    require_var STRIPE_PUBLISHABLE_KEY_LIVE
    require_var STRIPE_WEBHOOK_SECRET_LIVE
  fi

  log "target: $(remote_target)"
  log "domain: https://${DEPLOY_DOMAIN}"
  log "path: ${DEPLOY_PATH}"
  log "image: ${IMAGE_REF}"

  local tmp_dir="" env_tmp="" caddy_snippet_tmp="" compose_tmp=""
  tmp_dir="$(mktemp -d)"
  env_tmp="${tmp_dir}/server.env"
  caddy_snippet_tmp="${tmp_dir}/api-caddy-snippet.Caddyfile"
  compose_tmp="${tmp_dir}/docker-compose.image-only.yml"
  trap '[[ -n "${tmp_dir:-}" ]] && rm -rf "$tmp_dir"' EXIT

  write_server_env_file "$env_tmp"
  render_caddy_snippet >"$caddy_snippet_tmp"
  write_compose_file "$compose_tmp"

  log "checking SSH connectivity"
  ssh_remote "echo connected: \$(hostname)"

  log "checking docker + compose"
  ssh_remote "set -e
if ! command -v docker >/dev/null 2>&1; then
  echo 'docker missing on host' >&2
  exit 1
fi
docker compose version >/dev/null"

  if [[ -n "${REGISTRY_HOST:-}" && -n "${REGISTRY_USERNAME:-}" && -n "${REGISTRY_PASSWORD:-}" ]]; then
    log "logging into private registry ${REGISTRY_HOST}"
    # Password is sent over SSH stdin directly into docker login; it is never
    # placed in the remote command string, so special chars in the password are
    # safe and it will not appear in shell history.
    local target host_q user_q
    target="$(remote_target)"
    host_q="$(shell_quote "$REGISTRY_HOST")"
    user_q="$(shell_quote "$REGISTRY_USERNAME")"
    local args=()
    while IFS= read -r arg; do args+=("$arg"); done < <(ssh_args)
    printf '%s' "$REGISTRY_PASSWORD" | ssh "${args[@]}" "$target" \
      "docker login ${host_q} --username ${user_q} --password-stdin >/dev/null"
  elif [[ -n "${REGISTRY_HOST:-}" || -n "${REGISTRY_USERNAME:-}" || -n "${REGISTRY_PASSWORD:-}" ]]; then
    die "REGISTRY_HOST, REGISTRY_USERNAME, and REGISTRY_PASSWORD must be set together (or all left blank)"
  else
    log "registry credentials not set; assuming server is already docker login'd or image is public"
  fi

  log "creating minimal runtime directory"
  ssh_remote "set -euo pipefail
mkdir -p '${DEPLOY_PATH}/deploy' '${DEPLOY_PATH}/storage'
chmod 700 '${DEPLOY_PATH}'"

  log "uploading .env, image-only compose, and generated Caddy snippet"
  scp_to_remote "$env_tmp" "${DEPLOY_PATH}/.env"
  scp_to_remote "$compose_tmp" "${DEPLOY_PATH}/docker-compose.image-only.yml"
  scp_to_remote "$caddy_snippet_tmp" "${DEPLOY_PATH}/deploy/generated-api-caddy-snippet.Caddyfile"
  ssh_remote "chmod 600 '${DEPLOY_PATH}/.env'"

  log "pulling image"
  ssh_remote "cd '${DEPLOY_PATH}' && docker compose -f docker-compose.image-only.yml pull"

  log "running production preflight inside the image"
  local strict_flag=""
  if [[ "$DEPLOY_STRICT_PREFLIGHT" == "1" ]]; then
    strict_flag="--strict"
  fi
  ssh_remote "set -e
docker run --rm \
  --env-file '${DEPLOY_PATH}/.env' \
  -v '${DEPLOY_PATH}/.env:/tmp/server.env:ro' \
  '${IMAGE_REF}' \
  python scripts/check_prod_env.py --env /tmp/server.env ${strict_flag}"

  log "starting image-only API container on 127.0.0.1:8000"
  ssh_remote "cd '${DEPLOY_PATH}' && docker compose -f docker-compose.image-only.yml up -d && docker compose -f docker-compose.image-only.yml ps"

  log "waiting for local API health endpoint and verifying portal routes"
  ssh_remote "for i in \$(seq 1 30); do
  if curl -fsS http://127.0.0.1:8000/health >/dev/null 2>&1; then
    echo '[remote] /health OK'
    if curl -fsS http://127.0.0.1:8000/docs >/dev/null 2>&1 \\
        && curl -fsS http://127.0.0.1:8000/login >/dev/null 2>&1 \\
        && curl -fsS http://127.0.0.1:8000/dashboard >/dev/null 2>&1 \\
        && curl -fsS http://127.0.0.1:8000/openapi.json >/dev/null 2>&1; then
      echo '[remote] portal pages + /openapi.json OK locally'
      if curl -fsS http://127.0.0.1:8000/app.html >/dev/null 2>&1; then
        echo '[remote] WARN: /app.html is reachable in the container; .dockerignore drift?'
      fi
      if curl -fsS http://127.0.0.1:8000/admin.html >/dev/null 2>&1; then
        echo '[remote] WARN: /admin.html is reachable in the container; .dockerignore drift?'
      fi
      exit 0
    fi
    echo '[remote] portal routes failed; retrying...'
  fi
  sleep 5
done
echo '[remote] timed out waiting for API endpoints'
docker compose -f '${DEPLOY_PATH}/docker-compose.image-only.yml' logs --tail=200 || true
exit 1"

  if [[ "$DEPLOY_VERIFY_PUBLIC" == "1" ]]; then
    log "verifying public HTTPS routes through Caddy"
    local public_path public_status
    for public_path in / /login /register /dashboard /billing /docs /portal.css /portal.js /health; do
      public_status="$(curl -k -s -o /dev/null -w '%{http_code}' "https://${DEPLOY_DOMAIN}${public_path}")"
      [[ "$public_status" == "200" ]] \
        || die "expected ${public_path} to be 200, got ${public_status}"
    done

    local blocked_path
    for blocked_path in /app.html /admin.html /openapi.json /_swagger /admin/users; do
      public_status="$(curl -k -s -o /dev/null -w '%{http_code}' "https://${DEPLOY_DOMAIN}${blocked_path}")"
      [[ "$public_status" == "404" ]] \
        || die "expected ${blocked_path} to be 404, got ${public_status}"
    done
    log "public verification OK"
  else
    log "skipping public HTTPS verification (DEPLOY_VERIFY_PUBLIC=0)"
  fi

  if [[ "$DEPLOY_IMAGE_PRUNE_SOURCE" == "1" ]]; then
    log "pruning source checkout from ${DEPLOY_PATH} (preserving .env, storage, deploy, compose)"
    ssh_remote "set -euo pipefail
cd '${DEPLOY_PATH}'
find . -mindepth 1 -maxdepth 1 \
  ! -name '.env' \
  ! -name 'storage' \
  ! -name 'deploy' \
  ! -name 'docker-compose.image-only.yml' \
  -exec rm -rf {} +
ls -la"
  else
    log "source pruning disabled (set DEPLOY_IMAGE_PRUNE_SOURCE=1 after first successful image-only deploy)"
  fi

  log "image-only deployment complete"
  log "API is running locally on the server: http://127.0.0.1:8000"
  log "Caddy snippet uploaded to: ${DEPLOY_PATH}/deploy/generated-api-caddy-snippet.Caddyfile"
}

main "$@"
