"""Reader-facing reusable knowledge for every shensha supported by the analyser.

The copy deliberately treats shensha as secondary cultural cues rather than
event guarantees.  Page composers may add chart-specific placement and
relation facts, but should not strengthen these generic descriptions into
deterministic claims.
"""

from __future__ import annotations


SHENSHA_LIBRARY: tuple[dict[str, str], ...] = (
    {
        "code": "SHENSHA:GUCHEN", "name": "孤辰", "kind": "煞", "cluster": "内在与边界",
        "tagline": "给独处留一间房",
        "summary": "孤辰常被用来提示独立、自我消化和对私人空间的需要。它不等于注定孤独，更像是在人际往来之外，仍要保留一段独自整理思绪的时间。",
        "reading": "落在不同柱位，会把这种边界感带到早年环境、工作协作、亲密相处或长期规划中。",
        "caveat": "不要据此判断婚姻成败；应继续观察日支、财官、合冲与现实选择。",
        "visual": "一位独坐屏风旁整理书卷的文士，身边只有一盏灯与一方坐榻；工笔人物图鉴，米白纸底，无文字。",
    },
    {
        "code": "SHENSHA:GUASU", "name": "寡宿", "kind": "煞", "cluster": "内在与边界",
        "tagline": "安静，不等于疏离",
        "summary": "寡宿常提示情绪表达较克制，许多感受先在心里沉淀，再决定是否说出。它的积极面是自持与专注，难处则是别人未必及时读懂你的需要。",
        "reading": "宜结合它所在宫位，看哪一类关系最需要主动说明感受，而不是只靠默契。",
        "caveat": "这是一种交流节奏的提示，不是孤独、离异或失去伴侣的结论。",
        "visual": "一位安静抚琴的成年人物与半掩屏风、白梅瓶，神态自持而非哀伤；工笔人物图鉴，无文字。",
    },
    {
        "code": "SHENSHA:HONGLUAN", "name": "红鸾", "kind": "神", "cluster": "人际与机缘",
        "tagline": "关系开始流动",
        "summary": "红鸾是传统关系意象，常用来提示亲近、合作与情感表达的机会变得更容易被看见。它既可落在感情，也可表现为人际气氛转暖。",
        "reading": "原局看长期的关系表达方式，大运流年出现时再观察具体阶段的社交与合作变化。",
        "caveat": "有红鸾不等于必然结婚，仍要结合日支、配偶星和现实关系状态。",
        "visual": "两位成年人物交换红色绶带与花笺，旁配海棠和双喜结但不作婚礼场面；新工笔人物图鉴，无文字。",
    },
    {
        "code": "SHENSHA:TIANXI", "name": "天喜", "kind": "神", "cluster": "人际与机缘",
        "tagline": "值得分享的好消息",
        "summary": "天喜强调喜悦、庆贺与共同参与的气氛。它常提示事情更容易通过人与人的互动获得推动，也提醒把成果与身边人分享。",
        "reading": "看它落在哪一柱，便可判断喜悦更接近家庭、工作、亲密生活还是未来计划。",
        "caveat": "它描述的是气氛和机会窗口，不保证某一件喜事按时发生。",
        "visual": "一位人物提朱红宫灯，身边以喜鹊、石榴花和礼盒作喜庆陪衬；年画与工笔融合，无文字。",
    },
    {
        "code": "SHENSHA:TIANDEGUIREN", "name": "天德贵人", "kind": "神", "cluster": "支持与帮助",
        "tagline": "宽厚带来回旋余地",
        "summary": "天德贵人常被理解为缓和矛盾、得到善意回应的辅助线索。它更像一种处理问题的方式：守住分寸、愿意体谅，事情便较容易出现转圜。",
        "reading": "先看落柱，再看是否与命局主线相连；有力时常表现为长辈、制度或关键人物的善意支持。",
        "caveat": "贵人不是替你完成事情的人，真正的帮助仍需由选择、行动和关系积累承接。",
        "visual": "温厚的中年文官手提明灯、伸手相迎，深青与米白宋制服饰，圆形金线框；工笔人物图鉴，无文字。",
    },
    {
        "code": "SHENSHA:YUEDE", "name": "月德贵人", "kind": "神", "cluster": "支持与帮助",
        "tagline": "柔和，也是解决问题的力量",
        "summary": "月德贵人强调圆融、体谅和细致的人情判断。面对僵局时，它提示通过缓一步、换一种说法或照顾彼此处境来创造空间。",
        "reading": "若落在外层宫位，常体现为环境中的善缘；落在日时，则更接近日常相处与长期做事风格。",
        "caveat": "月德只能作为辅助线索，不能抵消命局中所有冲突和现实风险。",
        "visual": "气质温和的成年女性文士手持圆扇与兰枝，姿态从容、色彩月白与浅青；工笔人物图鉴，无文字。",
    },
    {
        "code": "SHENSHA:TIANYI", "name": "天乙贵人", "kind": "神", "cluster": "支持与帮助",
        "tagline": "在关键处得到一只手",
        "summary": "天乙贵人常提示资源、经验或关键人物的援手。它的重点不是凭空幸运，而是当你愿意求助、协作和建立信任时，外部支持更容易接得上。",
        "reading": "结合落柱可辨帮助来自何种生活领域，再看与十神和干支关系是否形成实质连接。",
        "caveat": "不能只凭贵人标签判断事业层级或人生顺逆。",
        "visual": "可靠的成年侍者一手持伞、一手递出绳索与卷册，表达关键处援手；工笔人物图鉴，无文字。",
    },
    {
        "code": "SHENSHA:WENCHANG", "name": "文昌贵人", "kind": "神", "cluster": "学习与表达",
        "tagline": "把复杂的事说明白",
        "summary": "文昌贵人常关联学习、表达、整理与呈现。它提示对知识结构、文字语言或清晰沟通较为敏感，也适合通过持续训练把想法变成作品。",
        "reading": "看落柱和对应十神，可进一步区分是早期学习、工作表达、个人创作还是长期成果。",
        "caveat": "文昌不是考试成绩保证，能力仍要依靠训练、方法和投入。",
        "visual": "端坐书案前整理长卷的文士，配毛笔、砚台与成叠书册，构图清爽；工笔人物图鉴，无可读文字。",
    },
    {
        "code": "SHENSHA:YANGREN", "name": "羊刃", "kind": "煞", "cluster": "行动与权责",
        "tagline": "锋芒要有刀鞘",
        "summary": "羊刃象征强劲、直接与不退让的执行力。用得好是决断、承压和保护边界；失去节制时，则容易在速度、语气或竞争中走得过满。",
        "reading": "必须结合日主强弱、所在柱位和冲合制化，才能判断这股力量如何被使用。",
        "caveat": "不能从羊刃直接推断事故、伤病或暴力事件。",
        "visual": "一位沉稳武者双手将古剑收入刀鞘，动作克制、没有战斗；工笔人物图鉴，无文字。",
    },
    {
        "code": "SHENSHA:LUSHEN", "name": "禄神", "kind": "神", "cluster": "资源与生活",
        "tagline": "把能力变成稳定所得",
        "summary": "禄神偏向稳定资源、工作回报与生活支撑。它提示通过持续投入和可重复的能力，较容易形成看得见、接得住的成果。",
        "reading": "落在不同柱位，会分别侧重家庭基础、职业环境、日常生活或长期积累。",
        "caveat": "禄神不等于必然富贵，仍要看财星、格局、运势和现实经营。",
        "visual": "一只温驯白鹿立于谷穗、粮囊与算盘旁，以鹿谐禄，构图丰足不俗艳；工笔瑞兽器物图，无文字。",
    },
    {
        "code": "SHENSHA:HONGYAN", "name": "红艳煞", "kind": "煞", "cluster": "人际与机缘",
        "tagline": "吸引力也需要边界",
        "summary": "红艳煞常被用来描述容易被注意、情感感受鲜明或审美表达具有吸引力。它的课题不是压低魅力，而是让关系期待、表达分寸与现实承诺保持一致。",
        "reading": "结合落柱与桃花、财官、日支及合冲关系，判断吸引力主要在哪类场景出现。",
        "caveat": "不能据此评价品行，也不能直接判断感情纠纷。",
        "visual": "衣着雅致的成年人物手持山茶花与折扇，红色醒目但姿态克制，旁设一扇屏风表达边界；新工笔人物图鉴，无文字。",
    },
    {
        "code": "SHENSHA:JIANGXING", "name": "将星", "kind": "神", "cluster": "行动与权责",
        "tagline": "把人和事组织起来",
        "summary": "将星强调担当、组织和在关键时刻作决定的倾向。它适合被理解为带队、协调与承担结果，而不只是职位或权力。",
        "reading": "结合所在宫位和官杀、比劫，可判断这种担当更多发生在工作、家庭还是个人项目。",
        "caveat": "有将星不等于必然成为领导，真正的影响力需要能力与责任感支持。",
        "visual": "不着战甲的古代将领手持卷起的旌旗与调度图，神态坚定、无战争场面；工笔人物图鉴，无文字。",
    },
    {
        "code": "SHENSHA:HUAGAI", "name": "华盖", "kind": "煞", "cluster": "内在与边界",
        "tagline": "独立审美，自成天地",
        "summary": "华盖常与独立思考、审美感受、精神兴趣和不随众的表达方式联系在一起。它能带来沉浸与创造，也可能让交流显得更有门槛。",
        "reading": "看落柱可区分它更接近学习创作、职业风格、亲密生活还是长期精神追求。",
        "caveat": "华盖不等于孤僻或宗教身份，更不能单独判断婚恋。",
        "visual": "一位独立创作的文士坐于素色华盖下，身边放琴、香炉与未完成画卷；工笔人物图鉴，无文字。",
    },
    {
        "code": "SHENSHA:YIMA", "name": "驿马", "kind": "中性神煞", "cluster": "迁移与变化",
        "tagline": "在移动中打开空间",
        "summary": "驿马象征移动、转换、出行与环境变化。它既可能表现为地理迁移，也可能是岗位、项目、生活节奏或视野的持续切换。",
        "reading": "结合落柱和大运流年，辨别变化是长期底色还是阶段性主题，并继续看冲合所指向的领域。",
        "caveat": "驿马不等于必然远走，也不直接代表奔波辛苦。",
        "visual": "一位整装待发的古代驿使牵着温驯骏马，配旅行包袱与驿牌，不画远景；工笔人物图鉴，无文字。",
    },
    {
        "code": "SHENSHA:JIESHA", "name": "劫煞", "kind": "中性神煞", "cluster": "迁移与变化",
        "tagline": "越快的局面，越要守住次序",
        "summary": "劫煞常提示竞争、抢时间或资源快速流动的场景。积极面是反应快、敢于突破；需要留意的是不要在急迫中忽略步骤、边界和复核。",
        "reading": "结合所在柱位与比劫、财星及冲刑关系，判断哪类事务更需要风险预案。",
        "caveat": "不能从劫煞直接推断失窃、破财或灾祸。",
        "visual": "一位行动迅速的成年人物正在系紧护腕和绳结，旁置封好的钱袋与清单，强调复核；工笔人物器物图，无文字。",
    },
    {
        "code": "SHENSHA:WANGSHEN", "name": "亡神", "kind": "煞", "cluster": "内在与边界",
        "tagline": "专注时，也别失去全局",
        "summary": "亡神常被用来提示心思深入、对细节或隐性信息敏感。投入过深时，也可能暂时忽略周围变化，因此需要定期回到全局复盘。",
        "reading": "结合落柱可看这种深度注意力主要落在哪类生活领域，再与印星、食伤和冲合共同阅读。",
        "caveat": "它不是遗失、疾病或精神问题的确定信号。",
        "visual": "一位专注查看细密地图的文士，另一手持提灯，旁有展开与收拢的双层卷轴；工笔人物图鉴，无文字。",
    },
    {
        "code": "SHENSHA:TAOHUA", "name": "桃花", "kind": "中性神煞", "cluster": "人际与机缘",
        "tagline": "被看见，也看见别人",
        "summary": "桃花体现社交感受力、审美表达和被注意的可能。它可以作用于感情，也可体现为客户缘、公众表达、艺术气质或人际活跃。",
        "reading": "要结合落柱、日支、财官和合冲，区分它是自然亲和、表达优势，还是关系边界的课题。",
        "caveat": "桃花不等于滥情，也不保证恋爱或婚姻事件。",
        "visual": "一位气质明朗的成年人物手执桃枝，与两只喜鹊和折扇构成社交与审美意象；新工笔人物花鸟图，无文字。",
    },
    {
        "code": "SHENSHA:TAIJIGUIREN", "name": "太极贵人", "kind": "神", "cluster": "学习与表达",
        "tagline": "喜欢追问事物为何如此",
        "summary": "太极贵人常关联抽象理解、体系意识与对文化、哲思或规律的兴趣。它提示不满足于表面答案，愿意寻找事物背后的联系。",
        "reading": "结合印星、食伤及所在宫位，可进一步观察这种理解力如何转化为学习、研究或表达。",
        "caveat": "它不是智力等级证明，也不表示一定从事玄学或宗教。",
        "visual": "一位年长学者在圆案上整理天文仪、算筹与两卷互相对应的书，表现体系思考；工笔人物博古图，无文字。",
    },
    {
        "code": "SHENSHA:KONGWANG", "name": "空亡", "kind": "煞", "cluster": "内在与边界",
        "tagline": "暂时落空，也是在重新定义",
        "summary": "空亡常提示某些经验不容易按原本期待落实，或需要经过转换才能显出价值。它也可能带来对形式的超脱，以及重新理解得失的能力。",
        "reading": "必须看空在何柱、何支，以及是否被合冲填实；不同位置的表现差异很大。",
        "caveat": "空亡不是一律无效，更不能把所在宫位简单判成不存在。",
        "visual": "一位人物面对一只打开却暂时空置的画框与半透明纱幕，手中保留尚未落笔的卷轴；工笔人物图鉴，无文字。",
    },
    {
        "code": "SHENSHA:SANQIGUIREN", "name": "三奇贵人", "kind": "贵人", "cluster": "学习与表达",
        "tagline": "不同能力在一处汇合",
        "summary": "三奇贵人强调组合与协同：几种不同性质的能力若能按次序配合，容易形成独特解决方案。它适合读作跨界、整合和非常规路径。",
        "reading": "三奇有严格组合条件，需先确认排列与位置成立，再看是否得到月令和全局支持。",
        "caveat": "不能只见相关天干便称三奇，也不等于天然高人一等。",
        "visual": "三位不同专长的成年人物围绕圆案协作，案上分别放笔、尺度与印章，色彩协调；工笔群像图鉴，无文字。",
    },
    {
        "code": "SHENSHA:FUXINGGUIREN", "name": "福星贵人", "kind": "贵人", "cluster": "支持与帮助",
        "tagline": "善缘让日常多一点余裕",
        "summary": "福星贵人常被理解为生活中的善意、顺手与缓冲。它不一定表现为戏剧性的好运，更多时候是有人愿意配合、事情留有余地。",
        "reading": "结合落柱可看善缘更接近家庭背景、工作关系、个人生活还是未来成果。",
        "caveat": "福星不能替代现实计划，也不能抵消所有不利结构。",
        "visual": "一位亲切的成年主人正在分茶待客，旁有果盘、福袋与开着的门，气氛日常温暖；工笔人物图鉴，无文字。",
    },
    {
        "code": "SHENSHA:KUIGANG", "name": "魁罡", "kind": "贵人", "cluster": "行动与权责",
        "tagline": "原则鲜明，行动有骨架",
        "summary": "魁罡常被用来描述意志坚定、标准明确和不轻易妥协。成熟的表达是守原则又能承担后果；失衡时则可能过硬，难以听见不同意见。",
        "reading": "魁罡以特定日柱成立，必须结合日主强弱、官杀与全局制化阅读。",
        "caveat": "不能据此判断性别角色、婚姻好坏或暴烈性格。",
        "visual": "一位刚毅但克制的成年武官立于石柱前，双手执未出鞘长剑，姿态端正无战斗；工笔人物图鉴，无文字。",
    },
    {
        "code": "SHENSHA:GUOYINGUIREN", "name": "国印贵人", "kind": "贵人", "cluster": "行动与权责",
        "tagline": "在规则中建立可信度",
        "summary": "国印贵人强调制度意识、凭证、责任和可被托付。它常提示适合把经验沉淀为流程，让他人能够确认、复用和信任。",
        "reading": "结合官印、落柱和职业环境，观察它更偏向管理、专业认证还是公共责任。",
        "caveat": "国印不等于必然进入体制或获得职位。",
        "visual": "一位负责文书的古代官员双手捧无字印盒，旁配封存卷轴与档案柜；工笔人物博古图，无可读文字。",
    },
    {
        "code": "SHENSHA:DEXIUGUIREN", "name": "德秀贵人", "kind": "贵人", "cluster": "学习与表达",
        "tagline": "才华因分寸而更耐看",
        "summary": "德秀贵人把能力与品格放在一起阅读：不仅能做、能说，也重视如何做得妥当。它常表现为审美、表达、专业性与待人分寸的结合。",
        "reading": "需按月令组合确认成立，再看它落在哪些柱位以及是否与食伤、印星相连。",
        "caveat": "德秀是辅助标签，不可单独作为学历、品德或社会评价。",
        "visual": "一位文士在书案旁持兰枝与画卷，衣纹清雅、姿态谦和，表现才华与分寸；工笔人物图鉴，无文字。",
    },
    {
        "code": "SHENSHA:XUETANG", "name": "学堂", "kind": "神", "cluster": "学习与表达",
        "tagline": "把学习变成长期结构",
        "summary": "学堂强调系统学习、吸收知识和建立方法。它不只指学校，也可表现为职业训练、研究习惯和持续更新自己的能力。",
        "reading": "传统查法依据年柱纳音与对应地支查取，解读时再结合印星、食伤和所在柱位。",
        "caveat": "学堂不是学历或考试结果的保证。",
        "visual": "一位青年学者坐在书架与成叠典籍前做笔记，桌面有尺度和书签；工笔人物图鉴，无可读文字。",
    },
    {
        "code": "SHENSHA:CIGUAN", "name": "词馆", "kind": "贵人", "cluster": "学习与表达",
        "tagline": "让语言成为一门手艺",
        "summary": "词馆常关联文字、语言、叙述和正式表达。它提示对措辞、结构或文书较敏感，适合通过写作、讲述和专业呈现建立影响。",
        "reading": "结合落柱与食伤、印星，可辨它更偏学习积累、工作写作还是创作输出。",
        "caveat": "词馆不等于天生文采，也不能单独判断职业。",
        "visual": "一位成熟写作者执笔修改长卷，旁有镇纸、墨砚与封好的文书，神态专注；工笔人物图鉴，无可读文字。",
    },
    {
        "code": "SHENSHA:TIANCHUGUIREN", "name": "天厨贵人", "kind": "贵人", "cluster": "资源与生活",
        "tagline": "懂得照料，也懂得享用",
        "summary": "天厨贵人偏向饮食、照料、生活品质与资源调配。它可以是对滋味和材料的敏感，也可以是愿意用具体方式照顾自己与他人。",
        "reading": "结合食神、财星和所在宫位，看它更多体现为生活能力、审美品味、服务意识还是专业技能。",
        "caveat": "它不直接判断财富、体重、疾病或饮食职业。",
        "visual": "一位温和的古代厨者端着青瓷食盒，身旁陈列蒸笼、谷蔬与香料罐；工笔人物器物图，无文字。",
    },
    {
        "code": "SHENSHA:JINYU", "name": "金舆", "kind": "贵人", "cluster": "资源与生活",
        "tagline": "让生活有稳定的承载",
        "summary": "金舆常被理解为舒适、体面与被妥善承载的条件。它的现实表达可以是重视生活品质、工具环境和长期可持续的安排。",
        "reading": "结合财星、落柱和全局强弱，观察这种资源是外部条件，还是自己逐步建立的生活系统。",
        "caveat": "金舆不是豪车、财富或婚配条件的确定信号。",
        "visual": "一位衣着得体的成年人物站在精致木轮车与锦垫旁，手持钥匙形佩饰，表达承载与条件；工笔人物图鉴，无文字。",
    },
    {
        "code": "SHENSHA:ZAISHA", "name": "灾煞", "kind": "煞", "cluster": "迁移与变化",
        "tagline": "先做预案，再谈速度",
        "summary": "灾煞是传统风险提示，适合转译为对突发变化、环境扰动和安全细节的关注。它的价值在于提醒复核与预案，而不是制造恐惧。",
        "reading": "结合落柱、冲刑和大运流年，看哪类事务在特定阶段更需要留出缓冲。",
        "caveat": "不能由灾煞预测事故、疾病或具体灾祸。",
        "visual": "一位谨慎的行旅者正在检查斗笠、绳索、药箱与包袱，器物排列清楚，表现预案意识；工笔人物器物图，无文字。",
    },
    {
        "code": "SHENSHA:BAZHUAN", "name": "八专", "kind": "煞", "cluster": "内在与边界",
        "tagline": "投入很深，边界也要清楚",
        "summary": "八专常提示投入集中、感受鲜明和对关系或目标有较强黏着度。用得好是专注与深度；需要留心的是别让期待替代沟通。",
        "reading": "八专以特定日柱成立，宜结合日支、财官与合冲，观察亲密关系和个人投入方式。",
        "caveat": "不能把八专直接等同于感情不忠、婚姻不顺或品行问题。",
        "visual": "一位专注的织匠在双环木架上整理两色丝带，节点紧密但边界清楚；工笔人物图鉴，无文字。",
    },
    {
        "code": "SHENSHA:TONGZI", "name": "童子", "kind": "煞", "cluster": "内在与边界",
        "tagline": "保留敏感，也学习落地",
        "summary": "童子是民俗色彩较浓的传统标签。命书中只保留其象征层面：感受细、理想感强，或对环境变化较敏锐，需要通过规律生活和现实经验建立稳定感。",
        "reading": "若按传统查法成立，也只作为低权重文化附注，不参与核心格局和强弱判断。",
        "caveat": "不采用替身、关煞、寿命、疾病或婚姻灾难等民俗断语。",
        "visual": "一位年轻成年人物手持纸鸢与风铃，表情敏锐而平静，衣着素净、不作宗教形象；工笔人物图鉴，无文字。",
    },
    {
        "code": "SHENSHA:YINCHAYANCUO", "name": "阴差阳错", "kind": "煞", "cluster": "关系与校准",
        "tagline": "不是没有心意，而是节奏偶尔错开",
        "summary": "阴差阳错常用来提示表达、时机和彼此理解之间容易出现偏差。它更适合被读成沟通课题：重要决定多确认一步，把默认期待说清楚。",
        "reading": "它以特定日柱成立，应与日支、配偶星及原局合冲一起阅读，判断错位更可能出现在哪类互动中。",
        "caveat": "不能据此断定婚姻不顺、离异或错过某个特定的人。",
        "visual": "两位成年信使背向错开，各持半封书信，红蓝丝线先交错后在下方结成整齐结扣；工笔双人物图鉴，无文字。",
    },
    {
        "code": "SHENSHA:SHIEDABAI", "name": "十恶大败", "kind": "煞", "cluster": "资源与生活",
        "tagline": "资源使用要更有账目",
        "summary": "十恶大败是名称较重的传统日柱标签。现代命书宜把它降噪处理为资源规划提醒：面对收入、支出和承诺，适合保留记录、预算与复核。",
        "reading": "它以特定日柱成立，但是否形成现实压力，仍取决于财星、比劫、格局与运势。",
        "caveat": "不采用必然败家、破产或一生困顿等宿命化断语。",
        "visual": "一位账房人物核对算盘、分格账册与封口钱袋，桌面整齐，重点是预算与复核；工笔人物器物图，无可读文字。",
    },
    {
        "code": "SHENSHA:TIANYII", "name": "天医贵人", "kind": "贵人", "cluster": "照护与修复",
        "tagline": "理解身体，也尊重修复节奏",
        "summary": "天医贵人常关联照护、修复意识和对身心状态的敏感。它可以表现为愿意学习健康知识、照顾他人，或重视规律与恢复。",
        "reading": "结合所在柱位和食伤、印星，可观察照护倾向更接近日常生活、专业兴趣还是家庭责任。",
        "caveat": "天医不是医学资质，也不能用于疾病诊断、治疗建议或寿命判断。",
        "visual": "一位成年医者整理石臼、药秤与常见草本，神态专注温和，不作诊疗场面；工笔人物博古图，无文字。",
    },
)


SHENSHA_BY_CODE = {item["code"]: item for item in SHENSHA_LIBRARY}

SHENSHA_IMAGE_BY_CODE = {
    "SHENSHA:GUCHEN": "guchen-v1.png",
    "SHENSHA:GUASU": "guasu-v1.png",
    "SHENSHA:HONGLUAN": "hongluan-v1.png",
    "SHENSHA:TIANXI": "tianxi-v1.png",
    "SHENSHA:TIANDEGUIREN": "tiande-guiren-v2.png",
    "SHENSHA:YUEDE": "yuede-v1.png",
    "SHENSHA:TIANYI": "tianyi-v1.png",
    "SHENSHA:WENCHANG": "wenchang-v1.png",
    "SHENSHA:YANGREN": "yangren-v1.png",
    "SHENSHA:LUSHEN": "lushen-v1.png",
    "SHENSHA:HONGYAN": "hongyan-v1.png",
    "SHENSHA:JIANGXING": "jiangxing-v1.png",
    "SHENSHA:HUAGAI": "huagai-v1.png",
    "SHENSHA:YIMA": "yima-v1.png",
    "SHENSHA:JIESHA": "jiesha-v1.png",
    "SHENSHA:WANGSHEN": "wangshen-v1.png",
    "SHENSHA:TAOHUA": "taohua-v1.png",
    "SHENSHA:TAIJIGUIREN": "taijiguiren-v1.png",
    "SHENSHA:KONGWANG": "kongwang-v1.png",
    "SHENSHA:SANQIGUIREN": "sanqiguiren-v1.png",
    "SHENSHA:FUXINGGUIREN": "fuxingguiren-v1.png",
    "SHENSHA:KUIGANG": "kuigang-v1.png",
    "SHENSHA:GUOYINGUIREN": "guoyinguiren-v1.png",
    "SHENSHA:DEXIUGUIREN": "dexiuguiren-v1.png",
    "SHENSHA:XUETANG": "xuetang-v1.png",
    "SHENSHA:CIGUAN": "ciguan-v1.png",
    "SHENSHA:TIANCHUGUIREN": "tianchuguiren-v1.png",
    "SHENSHA:JINYU": "jinyu-v1.png",
    "SHENSHA:ZAISHA": "zaisha-v1.png",
    "SHENSHA:BAZHUAN": "bazhuan-v1.png",
    "SHENSHA:TONGZI": "tongzi-v1.png",
    "SHENSHA:YINCHAYANCUO": "yinchayancuo-v2.png",
    "SHENSHA:SHIEDABAI": "shiedabai-v1.png",
    "SHENSHA:TIANYII": "tianyii-v1.png",
}


def get_shensha_knowledge(code: str) -> dict[str, str]:
    """Return one immutable-by-convention shensha knowledge record."""

    result = dict(SHENSHA_BY_CODE[code])
    result["image"] = SHENSHA_IMAGE_BY_CODE[code]
    return result
